services:

  mysql:
    #image: mysql:5.5.48 # Es la versi贸n original que matchea con nacional, no funciona la opci贸n de Backups
    # image: mariadb:10.11.7 # Varsi贸n de MariaDB funcional, si se usa se debe modificar el script del listador
    image: mariadb:10.6.16 # Varsi贸n de MariaDB funcional, si se usa se debe modificar el script del listador
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
        - ./master:/master
        - ./backups:/backups
    # command: mysql -uroot -proot master < master/master.sql

  nacional:
    build:
      context: .
      dockerfile: Dockerfile-slim
    container_name: nacional
    restart: always
    network_mode: "host"
    # ports:
    #     - "9000:9000"
    #     - "8080:8080"
    volumes:
        - ./server:/server
        - ./client:/client
    depends_on:
        - mysql